//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `Servers.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface ServeursPrx extends com.zeroc.Ice.ObjectPrx
{
    default void sayHelloServeurs()
    {
        sayHelloServeurs(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sayHelloServeurs(java.util.Map<String, String> context)
    {
        _iceI_sayHelloServeursAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sayHelloServeursAsync()
    {
        return _iceI_sayHelloServeursAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sayHelloServeursAsync(java.util.Map<String, String> context)
    {
        return _iceI_sayHelloServeursAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sayHelloServeursAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sayHelloServeurs", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void playSong(int id)
    {
        playSong(id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void playSong(int id, java.util.Map<String, String> context)
    {
        _iceI_playSongAsync(id, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> playSongAsync(int id)
    {
        return _iceI_playSongAsync(id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> playSongAsync(int id, java.util.Map<String, String> context)
    {
        return _iceI_playSongAsync(id, context, false);
    }

    /**
     * @hidden
     * @param iceP_id -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_playSongAsync(int iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "playSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_id);
                 }, null);
        return f;
    }

    default Song[] getAllSongs()
    {
        return getAllSongs(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Song[] getAllSongs(java.util.Map<String, String> context)
    {
        return _iceI_getAllSongsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Song[]> getAllSongsAsync()
    {
        return _iceI_getAllSongsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Song[]> getAllSongsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllSongsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Song[]> _iceI_getAllSongsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Song[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllSongs", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Song[] ret;
                     ret = SongListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void uploadMP3(byte[] data, String path)
    {
        uploadMP3(data, path, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void uploadMP3(byte[] data, String path, java.util.Map<String, String> context)
    {
        _iceI_uploadMP3Async(data, path, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> uploadMP3Async(byte[] data, String path)
    {
        return _iceI_uploadMP3Async(data, path, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> uploadMP3Async(byte[] data, String path, java.util.Map<String, String> context)
    {
        return _iceI_uploadMP3Async(data, path, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param iceP_path -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_uploadMP3Async(byte[] iceP_data, String iceP_path, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "uploadMP3", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeByteSeq(iceP_data);
                     ostr.writeString(iceP_path);
                 }, null);
        return f;
    }

    default void addSong(String titre, String artiste, String album, int duration, String path)
    {
        addSong(titre, artiste, album, duration, path, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addSong(String titre, String artiste, String album, int duration, String path, java.util.Map<String, String> context)
    {
        _iceI_addSongAsync(titre, artiste, album, duration, path, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addSongAsync(String titre, String artiste, String album, int duration, String path)
    {
        return _iceI_addSongAsync(titre, artiste, album, duration, path, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addSongAsync(String titre, String artiste, String album, int duration, String path, java.util.Map<String, String> context)
    {
        return _iceI_addSongAsync(titre, artiste, album, duration, path, context, false);
    }

    /**
     * @hidden
     * @param iceP_titre -
     * @param iceP_artiste -
     * @param iceP_album -
     * @param iceP_duration -
     * @param iceP_path -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addSongAsync(String iceP_titre, String iceP_artiste, String iceP_album, int iceP_duration, String iceP_path, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                     ostr.writeString(iceP_artiste);
                     ostr.writeString(iceP_album);
                     ostr.writeInt(iceP_duration);
                     ostr.writeString(iceP_path);
                 }, null);
        return f;
    }

    default void delSong(int id, String path)
    {
        delSong(id, path, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void delSong(int id, String path, java.util.Map<String, String> context)
    {
        _iceI_delSongAsync(id, path, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> delSongAsync(int id, String path)
    {
        return _iceI_delSongAsync(id, path, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> delSongAsync(int id, String path, java.util.Map<String, String> context)
    {
        return _iceI_delSongAsync(id, path, context, false);
    }

    /**
     * @hidden
     * @param iceP_id -
     * @param iceP_path -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_delSongAsync(int iceP_id, String iceP_path, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "delSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_id);
                     ostr.writeString(iceP_path);
                 }, null);
        return f;
    }

    default void updateSong(int id, String titre, String artiste, String album, int duration)
    {
        updateSong(id, titre, artiste, album, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void updateSong(int id, String titre, String artiste, String album, int duration, java.util.Map<String, String> context)
    {
        _iceI_updateSongAsync(id, titre, artiste, album, duration, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> updateSongAsync(int id, String titre, String artiste, String album, int duration)
    {
        return _iceI_updateSongAsync(id, titre, artiste, album, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> updateSongAsync(int id, String titre, String artiste, String album, int duration, java.util.Map<String, String> context)
    {
        return _iceI_updateSongAsync(id, titre, artiste, album, duration, context, false);
    }

    /**
     * @hidden
     * @param iceP_id -
     * @param iceP_titre -
     * @param iceP_artiste -
     * @param iceP_album -
     * @param iceP_duration -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_updateSongAsync(int iceP_id, String iceP_titre, String iceP_artiste, String iceP_album, int iceP_duration, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "updateSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_id);
                     ostr.writeString(iceP_titre);
                     ostr.writeString(iceP_artiste);
                     ostr.writeString(iceP_album);
                     ostr.writeInt(iceP_duration);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServeursPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ServeursPrx.class, _ServeursPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServeursPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ServeursPrx.class, _ServeursPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServeursPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ServeursPrx.class, _ServeursPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServeursPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ServeursPrx.class, _ServeursPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ServeursPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ServeursPrx.class, _ServeursPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ServeursPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ServeursPrx.class, _ServeursPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ServeursPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ServeursPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ServeursPrx ice_adapterId(String newAdapterId)
    {
        return (ServeursPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ServeursPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ServeursPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ServeursPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ServeursPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ServeursPrx ice_invocationTimeout(int newTimeout)
    {
        return (ServeursPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ServeursPrx ice_connectionCached(boolean newCache)
    {
        return (ServeursPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ServeursPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ServeursPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServeursPrx ice_secure(boolean b)
    {
        return (ServeursPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ServeursPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ServeursPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServeursPrx ice_preferSecure(boolean b)
    {
        return (ServeursPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ServeursPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ServeursPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ServeursPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ServeursPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ServeursPrx ice_collocationOptimized(boolean b)
    {
        return (ServeursPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ServeursPrx ice_twoway()
    {
        return (ServeursPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ServeursPrx ice_oneway()
    {
        return (ServeursPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ServeursPrx ice_batchOneway()
    {
        return (ServeursPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ServeursPrx ice_datagram()
    {
        return (ServeursPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ServeursPrx ice_batchDatagram()
    {
        return (ServeursPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ServeursPrx ice_compress(boolean co)
    {
        return (ServeursPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ServeursPrx ice_timeout(int t)
    {
        return (ServeursPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ServeursPrx ice_connectionId(String connectionId)
    {
        return (ServeursPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ServeursPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ServeursPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Demo::Serveurs";
    }
}
